//CHARACTERS
export const SET_CHARACTERS = "SET_CHARACTERS";
export const SET_CHARACTER_PAGE = "SET_CHARACTER_PAGE";

export const ADD_RESIDENT = "ADD_RESIDENT";
export const CLEAR_RESIDENTS = "CLEAR_RESIDENTS";



//LOCATIONS
export const SET_LOCATIONS = "SET_LOCATIONS";
export const SET_LOCATION_PAGE = "SET_LOCATION_PAGE";
export const SET_LOCATION_DETAILS_URL = "SET_LOCATION_DETAILS_URL";


//EPISODES
export const SET_EPISODES= "SET_EPISODES";
export const SET_EPISODES_PAGE = "SET_EPISODES_PAGE";


// PAGINATION
export const SET_PAGE = "SET_PAGE";
