//CHARACTERS
export const SET_CHARACTERS = "SET_CHARACTERS";
export const SET_CHARACTER_PAGE = "SET_CHARACTER_PAGE";

//LOCATIONS
export const SET_LOCATIONS = "SET_LOCATIONS";
export const SET_LOCATION_PAGE = "SET_LOCATION_PAGE";

//EPISODES
export const SET_EPISODES= "SET_EPISODES";
export const SET_EPISODES_PAGE = "SET_EPISODES_PAGE";


// PAGINATION
export const SET_PAGE = "SET_PAGE";
